version: '3'

services:
  frontend:
    image: frontend-image
    ports:
      - "80:80"
    networks:
      - frontend-network

  backend:
    image: backend-image
    ports:
      - "5000:5000"
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network: